/**
 * Curated native Unicode emoji catalog and search helpers.
 *
 * Fully client-side, zero network dependencies, grouped by category with
 * shortcodes and common search keywords.
 */

export const EMOJI_CATEGORIES = Object.freeze([
  { id: 'recent', label: 'Recent', icon: '🕒' },
  { id: 'smileys', label: 'Smileys', icon: '😀' },
  { id: 'gestures', label: 'People', icon: '👋' },
  { id: 'nature', label: 'Nature', icon: '🌿' },
  { id: 'food', label: 'Food', icon: '☕' },
  { id: 'travel', label: 'Travel', icon: '🚲' },
  { id: 'activity', label: 'Activities', icon: '🎮' },
  { id: 'objects', label: 'Objects', icon: '💡' },
  { id: 'symbols', label: 'Symbols', icon: '❤️' },
]);

export const EMOJI_LIST = [
  // --- SMILEYS & EMOTION ---
  { emoji: '😀', shortcode: 'grinning', name: 'Grinning Face', category: 'smileys', keywords: ['smile', 'happy', 'grin'] },
  { emoji: '😃', shortcode: 'smiley', name: 'Grinning Face with Big Eyes', category: 'smileys', keywords: ['happy', 'joy', 'smile'] },
  { emoji: '😄', shortcode: 'smile', name: 'Grinning Face with Smiling Eyes', category: 'smileys', keywords: ['happy', 'pleased', 'laugh'] },
  { emoji: '😁', shortcode: 'beam', name: 'Beaming Face with Smiling Eyes', category: 'smileys', keywords: ['grin', 'teeth'] },
  { emoji: '😆', shortcode: 'laughing', name: 'Grinning Squinting Face', category: 'smileys', keywords: ['satisfied', 'haha'] },
  { emoji: '😅', shortcode: 'sweat_smile', name: 'Grinning Face with Sweat', category: 'smileys', keywords: ['hot', 'whew', 'relief'] },
  { emoji: '🤣', shortcode: 'rofl', name: 'Rolling on the Floor Laughing', category: 'smileys', keywords: ['lol', 'laughing', 'haha'] },
  { emoji: '😂', shortcode: 'joy', name: 'Face with Tears of Joy', category: 'smileys', keywords: ['cry', 'tears', 'laugh', 'haha'] },
  { emoji: '🙂', shortcode: 'slightly_smiling_face', name: 'Slightly Smiling Face', category: 'smileys', keywords: ['smile', 'mild'] },
  { emoji: '🙃', shortcode: 'upside_down_face', name: 'Upside-Down Face', category: 'smileys', keywords: ['silly', 'sarcasm', 'ironic'] },
  { emoji: '😉', shortcode: 'wink', name: 'Winking Face', category: 'smileys', keywords: ['flirt', 'joke'] },
  { emoji: '😊', shortcode: 'blush', name: 'Smiling Face with Smiling Eyes', category: 'smileys', keywords: ['warm', 'blush', 'cozy'] },
  { emoji: '😇', shortcode: 'innocent', name: 'Smiling Face with Halo', category: 'smileys', keywords: ['angel', 'pure'] },
  { emoji: '🥰', shortcode: 'smiling_face_with_3_hearts', name: 'Smiling Face with Hearts', category: 'smileys', keywords: ['love', 'adore'] },
  { emoji: '😍', shortcode: 'heart_eyes', name: 'Smiling Face with Heart-Eyes', category: 'smileys', keywords: ['love', 'crush'] },
  { emoji: '🤩', shortcode: 'star_struck', name: 'Star-Struck', category: 'smileys', keywords: ['star', 'amazed', 'wow'] },
  { emoji: '😘', shortcode: 'kissing_heart', name: 'Face Blowing a Kiss', category: 'smileys', keywords: ['kiss', 'love'] },
  { emoji: '😋', shortcode: 'yum', name: 'Face Savoring Food', category: 'smileys', keywords: ['delicious', 'tongue', 'tasty'] },
  { emoji: '😛', shortcode: 'stuck_out_tongue', name: 'Face with Tongue', category: 'smileys', keywords: ['playful', 'silly'] },
  { emoji: '😜', shortcode: 'stuck_out_tongue_winking_eye', name: 'Winking Face with Tongue', category: 'smileys', keywords: ['crazy', 'joke'] },
  { emoji: '🤪', shortcode: 'zany_face', name: 'Zany Face', category: 'smileys', keywords: ['goofy', 'wacky'] },
  { emoji: '😝', shortcode: 'squinting_tongue', name: 'Squinting Face with Tongue', category: 'smileys', keywords: ['prank', 'lol'] },
  { emoji: '🤑', shortcode: 'money_mouth_face', name: 'Money-Mouth Face', category: 'smileys', keywords: ['rich', 'dollar', 'coin'] },
  { emoji: '🤗', shortcode: 'hugs', name: 'Hugging Face', category: 'smileys', keywords: ['hug', 'warm', 'friendly'] },
  { emoji: '🤭', shortcode: 'hand_over_mouth', name: 'Face with Hand Over Mouth', category: 'smileys', keywords: ['oops', 'giggle'] },
  { emoji: '🤫', shortcode: 'shushing_face', name: 'Shushing Face', category: 'smileys', keywords: ['quiet', 'secret', 'shh'] },
  { emoji: '🤔', shortcode: 'thinking', name: 'Thinking Face', category: 'smileys', keywords: ['ponder', 'wonder', 'hmm'] },
  { emoji: '🤐', shortcode: 'zipper_mouth_face', name: 'Zipper-Mouth Face', category: 'smileys', keywords: ['silent', 'secret'] },
  { emoji: '🤨', shortcode: 'raised_eyebrow', name: 'Face with Raised Eyebrow', category: 'smileys', keywords: ['skeptical', 'doubt'] },
  { emoji: '😐', shortcode: 'neutral_face', name: 'Neutral Face', category: 'smileys', keywords: ['meh', 'blank'] },
  { emoji: '😑', shortcode: 'expressionless', name: 'Expressionless Face', category: 'smileys', keywords: ['blank', 'unimpressed'] },
  { emoji: '😶', shortcode: 'no_mouth', name: 'Face Without Mouth', category: 'smileys', keywords: ['mute', 'speechless'] },
  { emoji: '😏', shortcode: 'smirk', name: 'Smirking Face', category: 'smileys', keywords: ['smug', 'cheeky'] },
  { emoji: '😒', shortcode: 'unamused', name: 'Unamused Face', category: 'smileys', keywords: ['bored', 'unimpressed'] },
  { emoji: '🙄', shortcode: 'roll_eyes', name: 'Face with Rolling Eyes', category: 'smileys', keywords: ['eyeroll', 'frustrated'] },
  { emoji: '😬', shortcode: 'grimacing', name: 'Grimacing Face', category: 'smileys', keywords: ['awkward', 'eek'] },
  { emoji: '🤥', shortcode: 'lying_face', name: 'Lying Face', category: 'smileys', keywords: ['pinocchio', 'lie'] },
  { emoji: '😌', shortcode: 'relieved', name: 'Relieved Face', category: 'smileys', keywords: ['peace', 'calm'] },
  { emoji: '😔', shortcode: 'pensive', name: 'Pensive Face', category: 'smileys', keywords: ['sad', 'down'] },
  { emoji: '😪', shortcode: 'sleepy', name: 'Sleepy Face', category: 'smileys', keywords: ['tired', 'rest'] },
  { emoji: '🤤', shortcode: 'drooling_face', name: 'Drooling Face', category: 'smileys', keywords: ['tasty', 'drool'] },
  { emoji: '😴', shortcode: 'sleeping', name: 'Sleeping Face', category: 'smileys', keywords: ['sleep', 'zzz', 'night'] },
  { emoji: '😷', shortcode: 'mask', name: 'Face with Medical Mask', category: 'smileys', keywords: ['sick', 'health'] },
  { emoji: '🤒', shortcode: 'face_with_thermometer', name: 'Face with Thermometer', category: 'smileys', keywords: ['fever', 'ill'] },
  { emoji: '🤕', shortcode: 'head_bandage', name: 'Face with Head-Bandage', category: 'smileys', keywords: ['hurt', 'ouch'] },
  { emoji: '🤢', shortcode: 'nauseated_face', name: 'Nauseated Face', category: 'smileys', keywords: ['gross', 'sick'] },
  { emoji: '🤮', shortcode: 'vomiting_face', name: 'Face Vomiting', category: 'smileys', keywords: ['puke', 'gross'] },
  { emoji: '🥵', shortcode: 'hot_face', name: 'Hot Face', category: 'smileys', keywords: ['heat', 'summer', 'sweat'] },
  { emoji: '🥶', shortcode: 'cold_face', name: 'Cold Face', category: 'smileys', keywords: ['freeze', 'winter', 'ice'] },
  { emoji: '🥴', shortcode: 'woozy_face', name: 'Woozy Face', category: 'smileys', keywords: ['dizzy', 'intoxicated'] },
  { emoji: '😵', shortcode: 'dizzy_face', name: 'Dizzy Face', category: 'smileys', keywords: ['starstruck', 'confused'] },
  { emoji: '🤯', shortcode: 'exploding_head', name: 'Exploding Head', category: 'smileys', keywords: ['mindblown', 'shock'] },
  { emoji: '🤠', shortcode: 'cowboy_hat_face', name: 'Cowboy Hat Face', category: 'smileys', keywords: ['western', 'howdy'] },
  { emoji: '🥳', shortcode: 'partying_face', name: 'Partying Face', category: 'smileys', keywords: ['celebrate', 'cheers', 'party'] },
  { emoji: '😎', shortcode: 'sunglasses', name: 'Smiling Face with Sunglasses', category: 'smileys', keywords: ['cool', 'shades'] },
  { emoji: '🤓', shortcode: 'nerd_face', name: 'Nerd Face', category: 'smileys', keywords: ['geek', 'smart'] },
  { emoji: '🧐', shortcode: 'monocle_face', name: 'Face with Monocle', category: 'smileys', keywords: ['curious', 'inspect'] },
  { emoji: '😕', shortcode: 'confused', name: 'Confused Face', category: 'smileys', keywords: ['puzzled', 'huh'] },
  { emoji: '😟', shortcode: 'worried', name: 'Worried Face', category: 'smileys', keywords: ['nervous', 'concern'] },
  { emoji: '🙁', shortcode: 'slightly_frowning_face', name: 'Slightly Frowning Face', category: 'smileys', keywords: ['frown', 'disappointed'] },
  { emoji: '😮', shortcode: 'open_mouth', name: 'Face with Open Mouth', category: 'smileys', keywords: ['surprised', 'gasp'] },
  { emoji: '😯', shortcode: 'hushed', name: 'Hushed Face', category: 'smileys', keywords: ['quiet', 'stunned'] },
  { emoji: '😲', shortcode: 'astonished', name: 'Astonished Face', category: 'smileys', keywords: ['shocked', 'whoa'] },
  { emoji: '😳', shortcode: 'flushed', name: 'Flushed Face', category: 'smileys', keywords: ['embarrassed', 'blush'] },
  { emoji: '🥺', shortcode: 'pleading_face', name: 'Pleading Face', category: 'smileys', keywords: ['begging', 'puppy', 'please'] },
  { emoji: '😦', shortcode: 'frowning_open_mouth', name: 'Frowning Face with Open Mouth', category: 'smileys', keywords: ['dismayed', 'fear'] },
  { emoji: '😧', shortcode: 'anguished', name: 'Anguished Face', category: 'smileys', keywords: ['pain', 'shock'] },
  { emoji: '😨', shortcode: 'fearful', name: 'Fearful Face', category: 'smileys', keywords: ['scared', 'afraid'] },
  { emoji: '😰', shortcode: 'cold_sweat', name: 'Anxious Face with Sweat', category: 'smileys', keywords: ['nervous', 'panic'] },
  { emoji: '😥', shortcode: 'sad_relieved', name: 'Sad but Relieved Face', category: 'smileys', keywords: ['phew', 'sweat'] },
  { emoji: '😢', shortcode: 'cry', name: 'Crying Face', category: 'smileys', keywords: ['tear', 'sad'] },
  { emoji: '😭', shortcode: 'sob', name: 'Loudly Crying Face', category: 'smileys', keywords: ['bawl', 'heartbroken', 'sobbing'] },
  { emoji: '😱', shortcode: 'scream', name: 'Face Screaming in Fear', category: 'smileys', keywords: ['horror', 'scared', 'omg'] },
  { emoji: '😖', shortcode: 'confounded', name: 'Confounded Face', category: 'smileys', keywords: ['frustrated', 'quiver'] },
  { emoji: '😣', shortcode: 'persevere', name: 'Persevering Face', category: 'smileys', keywords: ['struggle', 'try'] },
  { emoji: '😞', shortcode: 'disappointed', name: 'Disappointed Face', category: 'smileys', keywords: ['gloomy', 'letdown'] },
  { emoji: '😓', shortcode: 'sweat', name: 'Downcast Face with Sweat', category: 'smileys', keywords: ['tired', 'exhausted'] },
  { emoji: '😩', shortcode: 'weary', name: 'Weary Face', category: 'smileys', keywords: ['tired', 'done'] },
  { emoji: '😫', shortcode: 'tired_face', name: 'Tired Face', category: 'smileys', keywords: ['exhausted', 'ugh'] },
  { emoji: '🥱', shortcode: 'yawning_face', name: 'Yawning Face', category: 'smileys', keywords: ['bored', 'sleepy'] },
  { emoji: '😤', shortcode: 'triumph', name: 'Face with Steam From Nose', category: 'smileys', keywords: ['proud', 'steaming', 'determined'] },
  { emoji: '😡', shortcode: 'rage', name: 'Pouting Face', category: 'smileys', keywords: ['angry', 'mad', 'red'] },
  { emoji: '😠', shortcode: 'angry', name: 'Angry Face', category: 'smileys', keywords: ['cross', 'irritated'] },
  { emoji: '🤬', shortcode: 'cursing_face', name: 'Face with Symbols on Mouth', category: 'smileys', keywords: ['swear', 'cuss', 'fuming'] },
  { emoji: '😈', shortcode: 'smiling_imp', name: 'Smiling Face with Horns', category: 'smileys', keywords: ['devil', 'mischief'] },
  { emoji: '👿', shortcode: 'imp', name: 'Angry Face with Horns', category: 'smileys', keywords: ['devil', 'evil'] },
  { emoji: '💀', shortcode: 'skull', name: 'Skull', category: 'smileys', keywords: ['dead', 'skeleton', 'danger', 'lmao'] },
  { emoji: '☠️', shortcode: 'skull_and_crossbones', name: 'Skull and Crossbones', category: 'smileys', keywords: ['poison', 'danger'] },
  { emoji: '💩', shortcode: 'poop', name: 'Pile of Poo', category: 'smileys', keywords: ['crap', 'turd'] },
  { emoji: '🤡', shortcode: 'clown_face', name: 'Clown Face', category: 'smileys', keywords: ['circus', 'fool'] },
  { emoji: '👻', shortcode: 'ghost', name: 'Ghost', category: 'smileys', keywords: ['spooky', 'halloween', 'boo'] },
  { emoji: '👽', shortcode: 'alien', name: 'Alien', category: 'smileys', keywords: ['ufo', 'space'] },
  { emoji: '👾', shortcode: 'space_invader', name: 'Alien Monster', category: 'smileys', keywords: ['retro', 'game', 'arcade'] },
  { emoji: '🤖', shortcode: 'robot', name: 'Robot', category: 'smileys', keywords: ['bot', 'droid', 'kiln', 'machine'] },
  { emoji: '🎃', shortcode: 'jack_o_lantern', name: 'Jack-O-Lantern', category: 'smileys', keywords: ['halloween', 'pumpkin'] },

  // --- GESTURES & BODY ---
  { emoji: '👋', shortcode: 'wave', name: 'Waving Hand', category: 'gestures', keywords: ['hello', 'hi', 'bye', 'greet'] },
  { emoji: '🤚', shortcode: 'raised_back_of_hand', name: 'Raised Back of Hand', category: 'gestures', keywords: ['hand', 'stop'] },
  { emoji: '🖐️', shortcode: 'hand_splayed', name: 'Hand with Fingers Splayed', category: 'gestures', keywords: ['five', 'spread'] },
  { emoji: '✋', shortcode: 'raised_hand', name: 'Raised Hand', category: 'gestures', keywords: ['highfive', 'stop'] },
  { emoji: '🖖', shortcode: 'vulcan_salute', name: 'Vulcan Salute', category: 'gestures', keywords: ['spock', 'peace', 'star trek'] },
  { emoji: '👌', shortcode: 'ok_hand', name: 'OK Hand', category: 'gestures', keywords: ['perfect', 'agree', 'alright'] },
  { emoji: '🤌', shortcode: 'pinched_fingers', name: 'Pinched Fingers', category: 'gestures', keywords: ['italian', 'gesture', 'what'] },
  { emoji: '🤏', shortcode: 'pinching_hand', name: 'Pinching Hand', category: 'gestures', keywords: ['small', 'tiny', 'little'] },
  { emoji: '✌️', shortcode: 'v', name: 'Victory Hand', category: 'gestures', keywords: ['peace', 'two', 'victory'] },
  { emoji: '🤞', shortcode: 'crossed_fingers', name: 'Crossed Fingers', category: 'gestures', keywords: ['luck', 'hope'] },
  { emoji: '🫰', shortcode: 'hand_with_index_and_thumb_crossed', name: 'Hand with Index Finger and Thumb Crossed', category: 'gestures', keywords: ['finger heart', 'money'] },
  { emoji: '🤟', shortcode: 'love_you_gesture', name: 'Love-You Gesture', category: 'gestures', keywords: ['ily', 'hand'] },
  { emoji: '🤘', shortcode: 'metal', name: 'Sign of the Horns', category: 'gestures', keywords: ['rock', 'metal'] },
  { emoji: '🤙', shortcode: 'call_me_hand', name: 'Call Me Hand', category: 'gestures', keywords: ['shaka', 'hang loose'] },
  { emoji: '👈', shortcode: 'point_left', name: 'Backhand Index Pointing Left', category: 'gestures', keywords: ['direction', 'left'] },
  { emoji: '👉', shortcode: 'point_right', name: 'Backhand Index Pointing Right', category: 'gestures', keywords: ['direction', 'right'] },
  { emoji: '👆', shortcode: 'point_up_2', name: 'Backhand Index Pointing Up', category: 'gestures', keywords: ['up', 'above'] },
  { emoji: '👇', shortcode: 'point_down', name: 'Backhand Index Pointing Down', category: 'gestures', keywords: ['down', 'below'] },
  { emoji: '☝️', shortcode: 'point_up', name: 'Index Pointing Up', category: 'gestures', keywords: ['first', 'one', 'point'] },
  { emoji: '👍', shortcode: '+1', name: 'Thumbs Up', category: 'gestures', keywords: ['yes', 'agree', 'good', 'like', 'approve'] },
  { emoji: '👎', shortcode: '-1', name: 'Thumbs Down', category: 'gestures', keywords: ['no', 'dislike', 'bad'] },
  { emoji: '✊', shortcode: 'fist_raised', name: 'Raised Fist', category: 'gestures', keywords: ['power', 'solidarity'] },
  { emoji: '👊', shortcode: 'fist_oncoming', name: 'Oncoming Fist', category: 'gestures', keywords: ['fistbump', 'punch'] },
  { emoji: '🤛', shortcode: 'fist_left', name: 'Left-Facing Fist', category: 'gestures', keywords: ['bump', 'punch'] },
  { emoji: '🤜', shortcode: 'fist_right', name: 'Right-Facing Fist', category: 'gestures', keywords: ['bump', 'punch'] },
  { emoji: '👏', shortcode: 'clap', name: 'Clapping Hands', category: 'gestures', keywords: ['applause', 'praise', 'bravo'] },
  { emoji: '🙌', shortcode: 'raised_hands', name: 'Raising Hands', category: 'gestures', keywords: ['celebration', 'hooray', 'yay'] },
  { emoji: '👐', shortcode: 'open_hands', name: 'Open Hands', category: 'gestures', keywords: ['welcome', 'hug'] },
  { emoji: '🤲', shortcode: 'palms_up_together', name: 'Palms Up Together', category: 'gestures', keywords: ['prayer', 'cupped'] },
  { emoji: '🤝', shortcode: 'handshake', name: 'Handshake', category: 'gestures', keywords: ['deal', 'agreement', 'partner'] },
  { emoji: '🙏', shortcode: 'pray', name: 'Folded Hands', category: 'gestures', keywords: ['please', 'thank you', 'thanks', 'hope'] },
  { emoji: '✍️', shortcode: 'writing_hand', name: 'Writing Hand', category: 'gestures', keywords: ['write', 'note'] },
  { emoji: '💪', shortcode: 'muscle', name: 'Flexed Biceps', category: 'gestures', keywords: ['strong', 'strength', 'power'] },
  { emoji: '👀', shortcode: 'eyes', name: 'Eyes', category: 'gestures', keywords: ['look', 'see', 'watch', 'peek'] },
  { emoji: '👁️', shortcode: 'eye', name: 'Eye', category: 'gestures', keywords: ['vision', 'stare'] },
  { emoji: '🫂', shortcode: 'people_hugging', name: 'People Hugging', category: 'gestures', keywords: ['hug', 'embrace', 'comfort'] },
  { emoji: '🏃', shortcode: 'runner', name: 'Person Running', category: 'gestures', keywords: ['run', 'fast', 'sprint'] },
  { emoji: '🚶', shortcode: 'walking', name: 'Person Walking', category: 'gestures', keywords: ['walk', 'stroll'] },
  { emoji: '💃', shortcode: 'dancer', name: 'Woman Dancing', category: 'gestures', keywords: ['dance', 'party'] },
  { emoji: '🕺', shortcode: 'man_dancing', name: 'Man Dancing', category: 'gestures', keywords: ['dance', 'groove'] },

  // --- NATURE & PLANTS ---
  { emoji: '🐶', shortcode: 'dog', name: 'Dog Face', category: 'nature', keywords: ['puppy', 'pet'] },
  { emoji: '🐱', shortcode: 'cat', name: 'Cat Face', category: 'nature', keywords: ['kitten', 'meow', 'pet'] },
  { emoji: '🦊', shortcode: 'fox', name: 'Fox', category: 'nature', keywords: ['wild', 'animal'] },
  { emoji: '🐻', shortcode: 'bear', name: 'Bear', category: 'nature', keywords: ['grizzly', 'forest'] },
  { emoji: '🐼', shortcode: 'panda_face', name: 'Panda', category: 'nature', keywords: ['bear', 'bamboo'] },
  { emoji: '🐨', shortcode: 'koala', name: 'Koala', category: 'nature', keywords: ['marsupial', 'australia'] },
  { emoji: '🦁', shortcode: 'lion', name: 'Lion', category: 'nature', keywords: ['king', 'mane'] },
  { emoji: '🐸', shortcode: 'frog', name: 'Frog', category: 'nature', keywords: ['toad', 'ribbit'] },
  { emoji: '🐵', shortcode: 'monkey_face', name: 'Monkey Face', category: 'nature', keywords: ['chimp', 'banana'] },
  { emoji: '🐧', shortcode: 'penguin', name: 'Penguin', category: 'nature', keywords: ['bird', 'ice', 'snow'] },
  { emoji: '🐦', shortcode: 'bird', name: 'Bird', category: 'nature', keywords: ['fly', 'chirp'] },
  { emoji: '🐤', shortcode: 'baby_chick', name: 'Baby Chick', category: 'nature', keywords: ['hatch', 'yellow'] },
  { emoji: '🦆', shortcode: 'duck', name: 'Duck', category: 'nature', keywords: ['quack', 'pond'] },
  { emoji: '🦅', shortcode: 'eagle', name: 'Eagle', category: 'nature', keywords: ['raptor', 'freedom'] },
  { emoji: '🦉', shortcode: 'owl', name: 'Owl', category: 'nature', keywords: ['wise', 'hoot', 'night'] },
  { emoji: '🦇', shortcode: 'bat', name: 'Bat', category: 'nature', keywords: ['night', 'spooky'] },
  { emoji: '🐺', shortcode: 'wolf', name: 'Wolf', category: 'nature', keywords: ['howl', 'pack'] },
  { emoji: '🐴', shortcode: 'horse', name: 'Horse', category: 'nature', keywords: ['equine', 'ride'] },
  { emoji: '🦄', shortcode: 'unicorn', name: 'Unicorn', category: 'nature', keywords: ['magic', 'fantasy'] },
  { emoji: '🐝', shortcode: 'bee', name: 'Honeybee', category: 'nature', keywords: ['honey', 'buzz', 'insect'] },
  { emoji: '🐛', shortcode: 'bug', name: 'Caterpillar', category: 'nature', keywords: ['insect', 'creep'] },
  { emoji: '🦋', shortcode: 'butterfly', name: 'Butterfly', category: 'nature', keywords: ['wings', 'pretty'] },
  { emoji: '🐌', shortcode: 'snail', name: 'Snail', category: 'nature', keywords: ['slow', 'shell'] },
  { emoji: '🐞', shortcode: 'beetle', name: 'Lady Beetle', category: 'nature', keywords: ['ladybug', 'spots'] },
  { emoji: '🐙', shortcode: 'octopus', name: 'Octopus', category: 'nature', keywords: ['tentacles', 'sea', 'ocean'] },
  { emoji: '🐬', shortcode: 'dolphin', name: 'Dolphin', category: 'nature', keywords: ['ocean', 'sea', 'swim'] },
  { emoji: '🐳', shortcode: 'whale', name: 'Spouting Whale', category: 'nature', keywords: ['ocean', 'marine'] },
  { emoji: '🦈', shortcode: 'shark', name: 'Shark', category: 'nature', keywords: ['ocean', 'predator'] },
  { emoji: '🌲', shortcode: 'evergreen_tree', name: 'Evergreen Tree', category: 'nature', keywords: ['pine', 'forest', 'wood'] },
  { emoji: '🌳', shortcode: 'deciduous_tree', name: 'Deciduous Tree', category: 'nature', keywords: ['tree', 'park', 'shade'] },
  { emoji: '🌴', shortcode: 'palm_tree', name: 'Palm Tree', category: 'nature', keywords: ['tropical', 'beach'] },
  { emoji: '🌵', shortcode: 'cactus', name: 'Cactus', category: 'nature', keywords: ['desert', 'spikes'] },
  { emoji: '🌾', shortcode: 'ear_of_rice', name: 'Sheaf of Rice', category: 'nature', keywords: ['grain', 'wheat'] },
  { emoji: '🌿', shortcode: 'herb', name: 'Herb', category: 'nature', keywords: ['leaf', 'green', 'botanical'] },
  { emoji: '☘️', shortcode: 'shamrock', name: 'Shamrock', category: 'nature', keywords: ['irish', 'clover'] },
  { emoji: '🍀', shortcode: 'four_leaf_clover', name: 'Four Leaf Clover', category: 'nature', keywords: ['lucky', 'clover'] },
  { emoji: '🍁', shortcode: 'maple_leaf', name: 'Maple Leaf', category: 'nature', keywords: ['autumn', 'fall', 'canada'] },
  { emoji: '🍂', shortcode: 'fallen_leaf', name: 'Fallen Leaf', category: 'nature', keywords: ['autumn', 'leaves'] },
  { emoji: '🍃', shortcode: 'leaves', name: 'Leaf Fluttering in Wind', category: 'nature', keywords: ['breeze', 'nature'] },
  { emoji: '🍄', shortcode: 'mushroom', name: 'Mushroom', category: 'nature', keywords: ['fungus', 'shroom'] },
  { emoji: '🌸', shortcode: 'cherry_blossom', name: 'Cherry Blossom', category: 'nature', keywords: ['flower', 'pink', 'spring'] },
  { emoji: '🌹', shortcode: 'rose', name: 'Rose', category: 'nature', keywords: ['flower', 'red', 'romance'] },
  { emoji: '🌻', shortcode: 'sunflower', name: 'Sunflower', category: 'nature', keywords: ['yellow', 'flower', 'summer'] },
  { emoji: '🌼', shortcode: 'blossom', name: 'Blossom', category: 'nature', keywords: ['flower', 'yellow'] },
  { emoji: '🌷', shortcode: 'tulip', name: 'Tulip', category: 'nature', keywords: ['flower', 'spring'] },
  { emoji: '🌱', shortcode: 'seedling', name: 'Seedling', category: 'nature', keywords: ['plant', 'sprout', 'growth'] },
  { emoji: '🪴', shortcode: 'potted_plant', name: 'Potted Plant', category: 'nature', keywords: ['indoor', 'houseplant'] },

  // --- FOOD & DRINK ---
  { emoji: '🍏', shortcode: 'green_apple', name: 'Green Apple', category: 'food', keywords: ['fruit', 'crisp'] },
  { emoji: '🍎', shortcode: 'apple', name: 'Red Apple', category: 'food', keywords: ['fruit', 'snack'] },
  { emoji: '🍊', shortcode: 'tangerine', name: 'Tangerine', category: 'food', keywords: ['orange', 'citrus'] },
  { emoji: '🍋', shortcode: 'lemon', name: 'Lemon', category: 'food', keywords: ['citrus', 'sour'] },
  { emoji: '🍌', shortcode: 'banana', name: 'Banana', category: 'food', keywords: ['fruit', 'peel'] },
  { emoji: '🍉', shortcode: 'watermelon', name: 'Watermelon', category: 'food', keywords: ['summer', 'melon'] },
  { emoji: '🍇', shortcode: 'grapes', name: 'Grapes', category: 'food', keywords: ['wine', 'fruit'] },
  { emoji: '🍓', shortcode: 'strawberry', name: 'Strawberry', category: 'food', keywords: ['berry', 'sweet'] },
  { emoji: '🫐', shortcode: 'blueberries', name: 'Blueberries', category: 'food', keywords: ['berry', 'fruit'] },
  { emoji: '🍒', shortcode: 'cherries', name: 'Cherries', category: 'food', keywords: ['fruit', 'cherry'] },
  { emoji: '🍑', shortcode: 'peach', name: 'Peach', category: 'food', keywords: ['fruit', 'sweet'] },
  { emoji: '🍍', shortcode: 'pineapple', name: 'Pineapple', category: 'food', keywords: ['tropical', 'fruit'] },
  { emoji: '🥥', shortcode: 'coconut', name: 'Coconut', category: 'food', keywords: ['tropical', 'nut'] },
  { emoji: '🥑', shortcode: 'avocado', name: 'Avocado', category: 'food', keywords: ['guac', 'green'] },
  { emoji: '🥐', shortcode: 'croissant', name: 'Croissant', category: 'food', keywords: ['bakery', 'pastry', 'french'] },
  { emoji: '🍞', shortcode: 'bread', name: 'Bread', category: 'food', keywords: ['toast', 'loaf', 'bakery'] },
  { emoji: '🧀', shortcode: 'cheese', name: 'Cheese Wedge', category: 'food', keywords: ['dairy', 'cheddar'] },
  { emoji: '🍳', shortcode: 'egg', name: 'Cooking', category: 'food', keywords: ['fry', 'breakfast', 'skillet'] },
  { emoji: '🥞', shortcode: 'pancakes', name: 'Pancakes', category: 'food', keywords: ['breakfast', 'syrup'] },
  { emoji: '🍔', shortcode: 'burger', name: 'Hamburger', category: 'food', keywords: ['fastfood', 'cheeseburger'] },
  { emoji: '🍟', shortcode: 'fries', name: 'French Fries', category: 'food', keywords: ['chips', 'potato'] },
  { emoji: '🍕', shortcode: 'pizza', name: 'Pizza', category: 'food', keywords: ['slice', 'cheese', 'pie'] },
  { emoji: '🌮', shortcode: 'taco', name: 'Taco', category: 'food', keywords: ['mexican', 'tortilla'] },
  { emoji: '🌯', shortcode: 'burrito', name: 'Burrito', category: 'food', keywords: ['wrap', 'mexican'] },
  { emoji: '🥗', shortcode: 'salad', name: 'Green Salad', category: 'food', keywords: ['healthy', 'greens'] },
  { emoji: '🍜', shortcode: 'ramen', name: 'Steaming Bowl', category: 'food', keywords: ['noodles', 'soup', 'ramen'] },
  { emoji: '🍣', shortcode: 'sushi', name: 'Sushi', category: 'food', keywords: ['japanese', 'fish', 'roll'] },
  { emoji: '🍱', shortcode: 'bento', name: 'Bento Box', category: 'food', keywords: ['japanese', 'lunch'] },
  { emoji: '🍦', shortcode: 'icecream', name: 'Soft Ice Cream', category: 'food', keywords: ['dessert', 'sweet', 'cone'] },
  { emoji: '🍩', shortcode: 'doughnut', name: 'Doughnut', category: 'food', keywords: ['donut', 'glaze', 'snack'] },
  { emoji: '🍪', shortcode: 'cookie', name: 'Cookie', category: 'food', keywords: ['chocolate', 'biscuit'] },
  { emoji: '🎂', shortcode: 'cake', name: 'Birthday Cake', category: 'food', keywords: ['celebrate', 'birthday'] },
  { emoji: '🍫', shortcode: 'chocolate_bar', name: 'Chocolate Bar', category: 'food', keywords: ['sweet', 'candy'] },
  { emoji: '🍿', shortcode: 'popcorn', name: 'Popcorn', category: 'food', keywords: ['movie', 'theater', 'cinema'] },
  { emoji: '☕', shortcode: 'coffee', name: 'Hot Beverage', category: 'food', keywords: ['cafe', 'espresso', 'tea', 'warm'] },
  { emoji: '🫖', shortcode: 'teapot', name: 'Teapot', category: 'food', keywords: ['tea', 'brew'] },
  { emoji: '🍵', shortcode: 'tea', name: 'Teacup Without Handle', category: 'food', keywords: ['green tea', 'matcha'] },
  { emoji: '🍺', shortcode: 'beer', name: 'Beer Mug', category: 'food', keywords: ['drink', 'pub', 'cheers'] },
  { emoji: '🍻', shortcode: 'beers', name: 'Clinking Beer Mugs', category: 'food', keywords: ['cheers', 'toast'] },
  { emoji: '🥂', shortcode: 'champagne', name: 'Clinking Glasses', category: 'food', keywords: ['celebrate', 'cheers', 'wine'] },
  { emoji: '🍷', shortcode: 'wine_glass', name: 'Wine Glass', category: 'food', keywords: ['red', 'drink'] },
  { emoji: '🧋', shortcode: 'boba', name: 'Bubble Tea', category: 'food', keywords: ['pearls', 'milktea'] },

  // --- TRAVEL & PLACES ---
  { emoji: '🚗', shortcode: 'car', name: 'Automobile', category: 'travel', keywords: ['drive', 'ride'] },
  { emoji: '🏎️', shortcode: 'race_car', name: 'Racing Car', category: 'travel', keywords: ['fast', 'f1', 'speed', 'kart'] },
  { emoji: '🚲', shortcode: 'bike', name: 'Bicycle', category: 'travel', keywords: ['cycle', 'downhill'] },
  { emoji: '🛵', shortcode: 'motor_scooter', name: 'Motor Scooter', category: 'travel', keywords: ['scooter', 'moped'] },
  { emoji: '🚂', shortcode: 'steam_locomotive', name: 'Locomotive', category: 'travel', keywords: ['train', 'railway'] },
  { emoji: '🚆', shortcode: 'train2', name: 'Train', category: 'travel', keywords: ['railway', 'commute'] },
  { emoji: '🚇', shortcode: 'metro', name: 'Metro', category: 'travel', keywords: ['subway', 'underground'] },
  { emoji: '✈️', shortcode: 'airplane', name: 'Airplane', category: 'travel', keywords: ['flight', 'fly', 'trip'] },
  { emoji: '🚀', shortcode: 'rocket', name: 'Rocket', category: 'travel', keywords: ['launch', 'space', 'to the moon'] },
  { emoji: '🛸', shortcode: 'flying_saucer', name: 'Flying Saucer', category: 'travel', keywords: ['ufo', 'alien'] },
  { emoji: '⛵', shortcode: 'sailboat', name: 'Sailboat', category: 'travel', keywords: ['boat', 'sea', 'wind'] },
  { emoji: '⚓', shortcode: 'anchor', name: 'Anchor', category: 'travel', keywords: ['harbor', 'nautical', 'sea'] },
  { emoji: '⛽', shortcode: 'fuelpump', name: 'Fuel Pump', category: 'travel', keywords: ['gas', 'petrol'] },
  { emoji: '🏕️', shortcode: 'camping', name: 'Camping', category: 'travel', keywords: ['tent', 'camp', 'outdoors'] },
  { emoji: '🏠', shortcode: 'house', name: 'House', category: 'travel', keywords: ['home', 'building'] },
  { emoji: '🏢', shortcode: 'office', name: 'Office Building', category: 'travel', keywords: ['city', 'work'] },
  { emoji: '🏛️', shortcode: 'classical_building', name: 'Classical Building', category: 'travel', keywords: ['court', 'museum'] },
  { emoji: '🏙️', shortcode: 'cityscape', name: 'Cityscape', category: 'travel', keywords: ['skyline', 'city', 'urban'] },
  { emoji: '🌅', shortcode: 'sunrise', name: 'Sunrise', category: 'travel', keywords: ['morning', 'dawn', 'sun'] },
  { emoji: '🌆', shortcode: 'city_dusk', name: 'Cityscape at Dusk', category: 'travel', keywords: ['evening', 'sunset'] },
  { emoji: '🌉', shortcode: 'bridge_at_night', name: 'Bridge at Night', category: 'travel', keywords: ['bridge', 'night'] },
  { emoji: '🌌', shortcode: 'milky_way', name: 'Milky Way', category: 'travel', keywords: ['stars', 'space', 'galaxy'] },
  { emoji: '🌧️', shortcode: 'cloud_with_rain', name: 'Cloud with Rain', category: 'travel', keywords: ['rain', 'weather', 'rain court'] },
  { emoji: '⛈️', shortcode: 'thunder_cloud_and_rain', name: 'Cloud with Lightning and Rain', category: 'travel', keywords: ['storm', 'thunder'] },
  { emoji: '🌈', shortcode: 'rainbow', name: 'Rainbow', category: 'travel', keywords: ['pride', 'color', 'sky'] },

  // --- ACTIVITIES & GAMES ---
  { emoji: '⚽', shortcode: 'soccer', name: 'Soccer Ball', category: 'activity', keywords: ['football', 'sport'] },
  { emoji: '🏀', shortcode: 'basketball', name: 'Basketball', category: 'activity', keywords: ['ball', 'hoop'] },
  { emoji: '🎱', shortcode: '8ball', name: 'Pool 8 Ball', category: 'activity', keywords: ['billiards', 'pool', 'game'] },
  { emoji: '🏓', shortcode: 'ping_pong', name: 'Ping Pong', category: 'activity', keywords: ['table tennis', 'paddle'] },
  { emoji: '🎯', shortcode: 'dart', name: 'Bullseye', category: 'activity', keywords: ['target', 'darts', 'hit'] },
  { emoji: '🎳', shortcode: 'bowling', name: 'Bowling', category: 'activity', keywords: ['strike', 'pins'] },
  { emoji: '🎮', shortcode: 'video_game', name: 'Video Game', category: 'activity', keywords: ['controller', 'play', 'arcade', 'gaming'] },
  { emoji: '🕹️', shortcode: 'joystick', name: 'Joystick', category: 'activity', keywords: ['retro', 'arcade', 'cabinet'] },
  { emoji: '🎰', shortcode: 'slot_machine', name: 'Slot Machine', category: 'activity', keywords: ['casino', 'luck'] },
  { emoji: '🎲', shortcode: 'game_die', name: 'Game Die', category: 'activity', keywords: ['dice', 'roll', 'random'] },
  { emoji: '♟️', shortcode: 'chess_pawn', name: 'Chess Pawn', category: 'activity', keywords: ['chess', 'board game'] },
  { emoji: '🎭', shortcode: 'performing_arts', name: 'Performing Arts', category: 'activity', keywords: ['theater', 'orpheum', 'drama'] },
  { emoji: '🎨', shortcode: 'art', name: 'Artist Palette', category: 'activity', keywords: ['paint', 'draw', 'creative'] },
  { emoji: '🎬', shortcode: 'clapper', name: 'Clapper Board', category: 'activity', keywords: ['movie', 'cinema', 'film', 'theater'] },
  { emoji: '🎤', shortcode: 'microphone', name: 'Microphone', category: 'activity', keywords: ['sing', 'karaoke', 'voice'] },
  { emoji: '🎧', shortcode: 'headphones', name: 'Headphone', category: 'activity', keywords: ['music', 'listen', 'audio'] },
  { emoji: '🎸', shortcode: 'guitar', name: 'Guitar', category: 'activity', keywords: ['music', 'rock'] },
  { emoji: '🎹', shortcode: 'musical_keyboard', name: 'Musical Keyboard', category: 'activity', keywords: ['piano', 'music'] },
  { emoji: '🏆', shortcode: 'trophy', name: 'Trophy', category: 'activity', keywords: ['win', 'first', 'champion'] },
  { emoji: '🥇', shortcode: 'first_place_medal', name: '1st Place Medal', category: 'activity', keywords: ['gold', 'win'] },
  { emoji: '🎟️', shortcode: 'admission_tickets', name: 'Admission Tickets', category: 'activity', keywords: ['ticket', 'cinema', 'show'] },

  // --- OBJECTS & TECH ---
  { emoji: '💡', shortcode: 'bulb', name: 'Light Bulb', category: 'objects', keywords: ['idea', 'light', 'lamp'] },
  { emoji: '🔦', shortcode: 'flashlight', name: 'Flashlight', category: 'objects', keywords: ['beam', 'torch'] },
  { emoji: '🕯️', shortcode: 'candle', name: 'Candle', category: 'objects', keywords: ['flame', 'cozy', 'warm'] },
  { emoji: '🔧', shortcode: 'wrench', name: 'Wrench', category: 'objects', keywords: ['tool', 'repair', 'fix'] },
  { emoji: '🔨', shortcode: 'hammer', name: 'Hammer', category: 'objects', keywords: ['build', 'construct', 'tool'] },
  { emoji: '⚙️', shortcode: 'gear', name: 'Gear', category: 'objects', keywords: ['cog', 'settings', 'mechanics'] },
  { emoji: '🧱', shortcode: 'brick', name: 'Brick', category: 'objects', keywords: ['wall', 'masonry'] },
  { emoji: '📺', shortcode: 'tv', name: 'Television', category: 'objects', keywords: ['screen', 'display', 'iptv'] },
  { emoji: '📻', shortcode: 'radio', name: 'Radio', category: 'objects', keywords: ['broadcast', 'tuner'] },
  { emoji: '💻', shortcode: 'computer', name: 'Laptop', category: 'objects', keywords: ['pc', 'code', 'tech'] },
  { emoji: '💾', shortcode: 'floppy_disk', name: 'Floppy Disk', category: 'objects', keywords: ['save', 'retro'] },
  { emoji: '📷', shortcode: 'camera', name: 'Camera', category: 'objects', keywords: ['photo', 'snap'] },
  { emoji: '📡', shortcode: 'satellite', name: 'Satellite Antenna', category: 'objects', keywords: ['relay', 'signal'] },
  { emoji: '🔋', shortcode: 'battery', name: 'Battery', category: 'objects', keywords: ['power', 'energy'] },
  { emoji: '🔑', shortcode: 'key', name: 'Key', category: 'objects', keywords: ['lock', 'access', 'secret'] },
  { emoji: '🚪', shortcode: 'door', name: 'Door', category: 'objects', keywords: ['entrance', 'gate'] },
  { emoji: '📦', shortcode: 'package', name: 'Package', category: 'objects', keywords: ['box', 'parcel'] },
  { emoji: '📜', shortcode: 'scroll', name: 'Scroll', category: 'objects', keywords: ['paper', 'document'] },
  { emoji: '📝', shortcode: 'memo', name: 'Memo', category: 'objects', keywords: ['note', 'write'] },
  { emoji: '🔍', shortcode: 'mag', name: 'Magnifying Glass Tilt Left', category: 'objects', keywords: ['search', 'find', 'zoom'] },
  { emoji: '🔒', shortcode: 'lock', name: 'Locked', category: 'objects', keywords: ['security', 'closed'] },
  { emoji: '🔓', shortcode: 'unlock', name: 'Unlocked', category: 'objects', keywords: ['open', 'security'] },
  { emoji: '🔔', shortcode: 'bell', name: 'Bell', category: 'objects', keywords: ['ring', 'notice', 'notification'] },
  { emoji: '💎', shortcode: 'gem', name: 'Gem Stone', category: 'objects', keywords: ['diamond', 'jewel'] },
  { emoji: '🎉', shortcode: 'tada', name: 'Party Popper', category: 'objects', keywords: ['celebrate', 'congrats', 'party'] },
  { emoji: '✨', shortcode: 'sparkles', name: 'Sparkles', category: 'objects', keywords: ['glitter', 'magic', 'shine', 'clean'] },

  // --- SYMBOLS & HEARTS ---
  { emoji: '❤️', shortcode: 'heart', name: 'Red Heart', category: 'symbols', keywords: ['love', 'like'] },
  { emoji: '🧡', shortcode: 'orange_heart', name: 'Orange Heart', category: 'symbols', keywords: ['love', 'warmth'] },
  { emoji: '💛', shortcode: 'yellow_heart', name: 'Yellow Heart', category: 'symbols', keywords: ['sun', 'friend'] },
  { emoji: '💚', shortcode: 'green_heart', name: 'Green Heart', category: 'symbols', keywords: ['nature', 'moss'] },
  { emoji: '💙', shortcode: 'blue_heart', name: 'Blue Heart', category: 'symbols', keywords: ['cold', 'water'] },
  { emoji: '💜', shortcode: 'purple_heart', name: 'Purple Heart', category: 'symbols', keywords: ['royal', 'violet'] },
  { emoji: '🤎', shortcode: 'brown_heart', name: 'Brown Heart', category: 'symbols', keywords: ['earth', 'wood'] },
  { emoji: '🖤', shortcode: 'black_heart', name: 'Black Heart', category: 'symbols', keywords: ['dark', 'goth'] },
  { emoji: '🤍', shortcode: 'white_heart', name: 'White Heart', category: 'symbols', keywords: ['pure', 'light'] },
  { emoji: '💔', shortcode: 'broken_heart', name: 'Broken Heart', category: 'symbols', keywords: ['heartbreak', 'sad'] },
  { emoji: '🔥', shortcode: 'fire', name: 'Fire', category: 'symbols', keywords: ['flame', 'hot', 'lit', 'hearth'] },
  { emoji: '⚡', shortcode: 'zap', name: 'High Voltage', category: 'symbols', keywords: ['lightning', 'thunder', 'electric'] },
  { emoji: '⭐', shortcode: 'star', name: 'Star', category: 'symbols', keywords: ['gold', 'favorite'] },
  { emoji: '🌟', shortcode: 'star2', name: 'Glowing Star', category: 'symbols', keywords: ['bright', 'shine'] },
  { emoji: '💫', shortcode: 'dizzy', name: 'Dizzy', category: 'symbols', keywords: ['sparkle', 'magic'] },
  { emoji: '💥', shortcode: 'boom', name: 'Collision', category: 'symbols', keywords: ['blast', 'impact'] },
  { emoji: '💯', shortcode: '100', name: 'Hundred Points', category: 'symbols', keywords: ['score', 'perfect', 'full'] },
  { emoji: '⚠️', shortcode: 'warning', name: 'Warning', category: 'symbols', keywords: ['alert', 'caution'] },
  { emoji: '⛔', shortcode: 'no_entry', name: 'No Entry', category: 'symbols', keywords: ['stop', 'prohibited'] },
  { emoji: '✅', shortcode: 'white_check_mark', name: 'Check Mark Button', category: 'symbols', keywords: ['ok', 'yes', 'done', 'complete'] },
  { emoji: '❌', shortcode: 'x', name: 'Cross Mark', category: 'symbols', keywords: ['no', 'delete', 'cancel'] },
  { emoji: '❓', shortcode: 'question', name: 'Question Mark', category: 'symbols', keywords: ['help', 'ask', 'why'] },
  { emoji: '❗', shortcode: 'exclamation', name: 'Exclamation Mark', category: 'symbols', keywords: ['important', 'alert'] },
  { emoji: '💬', shortcode: 'speech_balloon', name: 'Speech Balloon', category: 'symbols', keywords: ['chat', 'message', 'talk'] },
  { emoji: '👁️‍🗨️', shortcode: 'eye_speech_bubble', name: 'Eye in Speech Bubble', category: 'symbols', keywords: ['witness', 'look'] },
  { emoji: '◈', shortcode: 'diamond_bullet', name: 'Diamond Bullet', category: 'symbols', keywords: ['afterlight', 'world', 'symbol'] },
  { emoji: '✦', shortcode: 'four_pointed_star', name: 'Sparkle Star', category: 'symbols', keywords: ['afterlight', 'glow', 'star'] },
];

// Pre-build indexes for high-performance lookup
export const EMOJI_BY_CATEGORY = new Map();
for (const cat of EMOJI_CATEGORIES) {
  if (cat.id !== 'recent') {
    EMOJI_BY_CATEGORY.set(cat.id, []);
  }
}
for (const item of EMOJI_LIST) {
  const bucket = EMOJI_BY_CATEGORY.get(item.category);
  if (bucket) bucket.push(item);
}

const SHORTCODE_MAP = new Map();
for (const item of EMOJI_LIST) {
  SHORTCODE_MAP.set(item.shortcode.toLowerCase(), item);
}

/**
 * Searches the emoji catalog by query string.
 * Matches shortcode prefix first, then name, then keywords.
 *
 * @param {string} query
 * @param {number} [limit=24]
 * @returns {Array}
 */
export function searchEmoji(query, limit = 24) {
  const q = String(query || '').trim().toLowerCase().replace(/^:/, '');
  if (!q) return EMOJI_LIST.slice(0, limit);

  const exact = [];
  const prefix = [];
  const substring = [];

  for (const item of EMOJI_LIST) {
    const sc = item.shortcode.toLowerCase();
    if (sc === q) {
      exact.push(item);
    } else if (sc.startsWith(q)) {
      prefix.push(item);
    } else if (item.name.toLowerCase().includes(q) || item.keywords.some(k => k.includes(q))) {
      substring.push(item);
    }
    if (exact.length + prefix.length + substring.length >= limit * 2) break;
  }

  return [...exact, ...prefix, ...substring].slice(0, limit);
}

export function findEmojiByShortcode(shortcode) {
  const code = String(shortcode || '').trim().toLowerCase().replace(/^:/, '').replace(/:$/, '');
  return SHORTCODE_MAP.get(code) || null;
}
