defmodule Afterlight.Repo.Migrations.CreateConferencing do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:media_grants, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:player_id, :text, null: false)
      add(:worker_id, :text, null: false)
      add(:can_publish_audio, :boolean, null: false, default: true)
      add(:can_publish_video, :boolean, null: false, default: false)
      add(:can_publish_screen, :boolean, null: false, default: false)
      add(:issued_at, :utc_datetime_usec, null: false)
      add(:expires_at, :utc_datetime_usec, null: false)
      add(:revoked_at, :utc_datetime_usec)
      add(:revoke_reason, :text)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:call_id, :uuid, null: false)
    end

    create table(:calls, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
    end

    alter table(:media_grants) do
      modify(
        :call_id,
        references(:calls,
          column: :id,
          name: "media_grants_call_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:calls) do
      add(:room_key, :text, null: false)
      add(:mode, :text, null: false, default: "voice")
      add(:status, :text, null: false, default: "active")
      add(:max_participants, :bigint, null: false, default: 8)
      add(:worker_id, :text)
      add(:created_by_id, :text, null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:ended_at, :utc_datetime_usec)
    end

    create table(:call_memberships, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:player_id, :text, null: false)
      add(:state, :text, null: false, default: "joined")
      add(:joined_at, :utc_datetime_usec, null: false)
      add(:left_at, :utc_datetime_usec)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :call_id,
        references(:calls,
          column: :id,
          name: "call_memberships_call_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )
    end

    create(
      unique_index(:call_memberships, [:call_id, :player_id],
        name: "call_memberships_unique_member_index"
      )
    )
  end

  def down do
    drop(constraint(:call_memberships, "call_memberships_call_id_fkey"))

    drop_if_exists(
      unique_index(:call_memberships, [:call_id, :player_id],
        name: "call_memberships_unique_member_index"
      )
    )

    drop(table(:call_memberships))

    alter table(:calls) do
      remove(:ended_at)
      remove(:updated_at)
      remove(:inserted_at)
      remove(:created_by_id)
      remove(:worker_id)
      remove(:max_participants)
      remove(:status)
      remove(:mode)
      remove(:room_key)
    end

    drop(constraint(:media_grants, "media_grants_call_id_fkey"))

    alter table(:media_grants) do
      modify(:call_id, :uuid)
    end

    drop(table(:calls))

    drop(table(:media_grants))
  end
end
